// 使用proto3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0--rc3
// source: protobuf/goods/goods.proto

package goods

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GoodsReq) Reset() {
	*x = GoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_goods_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsReq) ProtoMessage() {}

func (x *GoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_goods_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsReq.ProtoReflect.Descriptor instead.
func (*GoodsReq) Descriptor() ([]byte, []int) {
	return file_protobuf_goods_goods_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price uint64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *GoodsRes) Reset() {
	*x = GoodsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_goods_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsRes) ProtoMessage() {}

func (x *GoodsRes) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_goods_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsRes.ProtoReflect.Descriptor instead.
func (*GoodsRes) Descriptor() ([]byte, []int) {
	return file_protobuf_goods_goods_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsRes) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_protobuf_goods_goods_proto protoreflect.FileDescriptor

var file_protobuf_goods_goods_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x22, 0x1a, 0x0a, 0x08, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x34, 0x0a, 0x08, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x38, 0x0a, 0x08, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x70,
	0x63, 0x12, 0x2c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x0f, 0x2e,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_goods_goods_proto_rawDescOnce sync.Once
	file_protobuf_goods_goods_proto_rawDescData = file_protobuf_goods_goods_proto_rawDesc
)

func file_protobuf_goods_goods_proto_rawDescGZIP() []byte {
	file_protobuf_goods_goods_proto_rawDescOnce.Do(func() {
		file_protobuf_goods_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_goods_goods_proto_rawDescData)
	})
	return file_protobuf_goods_goods_proto_rawDescData
}

var file_protobuf_goods_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_goods_goods_proto_goTypes = []interface{}{
	(*GoodsReq)(nil), // 0: goods.GoodsReq
	(*GoodsRes)(nil), // 1: goods.GoodsRes
}
var file_protobuf_goods_goods_proto_depIdxs = []int32{
	0, // 0: goods.GoodsRpc.GetGoods:input_type -> goods.GoodsReq
	1, // 1: goods.GoodsRpc.GetGoods:output_type -> goods.GoodsRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_goods_goods_proto_init() }
func file_protobuf_goods_goods_proto_init() {
	if File_protobuf_goods_goods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_goods_goods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_goods_goods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_goods_goods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_goods_goods_proto_goTypes,
		DependencyIndexes: file_protobuf_goods_goods_proto_depIdxs,
		MessageInfos:      file_protobuf_goods_goods_proto_msgTypes,
	}.Build()
	File_protobuf_goods_goods_proto = out.File
	file_protobuf_goods_goods_proto_rawDesc = nil
	file_protobuf_goods_goods_proto_goTypes = nil
	file_protobuf_goods_goods_proto_depIdxs = nil
}
