// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-feature-test/internal/dao/internal"
)

// internalUserDetailDao is internal type for wrapping internal DAO implements.
type internalUserDetailDao = *internal.UserDetailDao

// userDetailDao is the data access object for table user_detail.
// You can define custom methods on it to extend its functionality as you wish.
type userDetailDao struct {
	internalUserDetailDao
}

var (
	// UserDetail is globally public accessible object for table user_detail operations.
	UserDetail = userDetailDao{
		internal.NewUserDetailDao(),
	}
)

// Fill with you ideas below.
