// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-feature-test/internal/dao/internal"
)

// internalUserScoresDao is internal type for wrapping internal DAO implements.
type internalUserScoresDao = *internal.UserScoresDao

// userScoresDao is the data access object for table user_scores.
// You can define custom methods on it to extend its functionality as you wish.
type userScoresDao struct {
	internalUserScoresDao
}

var (
	// UserScores is globally public accessible object for table user_scores operations.
	UserScores = userScoresDao{
		internal.NewUserScoresDao(),
	}
)

// Fill with you ideas below.
